# Generated by Django 4.1.1 on 2022-09-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bean",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_num", models.CharField(max_length=20, unique=True)),
                ("purchase_date", models.CharField(max_length=25)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Brazil", "Brazil"),
                            ("Burundi", "Burundi"),
                            ("Colombia", "Colombia"),
                            ("Costa Rica", "Costa Rica"),
                            ("Dominican Republic", "Dominican Republic"),
                            ("Ecuador", "Ecuador"),
                            ("El Salvador", "El Salvador"),
                            ("Ethiopia", "Ethiopia"),
                            ("Guatemala", "Guatemala"),
                            ("Haiti", "Haiti"),
                            ("Honduras", "Honduras"),
                            ("India", "India"),
                            ("Indonesia", "Indonesia"),
                            ("Jamaica", "Jamaica"),
                            ("Kenya", "Kenya"),
                            ("Mexico", "Mexico"),
                            ("Nicaragua", "Nicaragua"),
                            ("Papua New Guinea", "Papua New Guinea"),
                            ("Peru", "Peru"),
                            ("Rwanda", "Rwanda"),
                            ("Tanzania", "Tanzania"),
                            ("United States", "United States"),
                            ("Uganda", "Uganda"),
                            ("Yemen", "Yemen"),
                            ("Zambia", "Zambia"),
                        ],
                        default="1",
                        max_length=50,
                    ),
                ),
                (
                    "varietal",
                    models.CharField(
                        choices=[
                            ("Blue Mountain", "Blue Mountain"),
                            ("Bourbon", "Bourbon"),
                            ("Catuai", "Catuai"),
                            ("Caturra", "Caturra"),
                            ("Ethiopia Heirloom", "Ethiopia Heirloom"),
                            ("Geisha", "Geisha"),
                            ("Java", "Java"),
                            ("Kona", "Kona"),
                            ("Mocha", "Mocha"),
                            ("Pachamara", "Pachamara"),
                            ("Sidamo", "Sidamo"),
                            ("SL28", "SL28"),
                            ("SL34", "SL34"),
                            ("Sulawesi", "Sulawesi"),
                            ("Sumatra", "Sumatra"),
                            ("Typica", "Typica"),
                        ],
                        default="1",
                        max_length=20,
                    ),
                ),
                (
                    "process",
                    models.CharField(
                        choices=[
                            ("Washed", "Washed"),
                            ("Natural", "Natural"),
                            ("Black Honey", "Black Honey"),
                            ("Red Honey", "Red Honey"),
                            ("Yellow Honey", "Yellow Honey"),
                            ("White Honey", "White Honey"),
                        ],
                        default="1",
                        max_length=15,
                    ),
                ),
                ("growing_region", models.CharField(max_length=25)),
                ("washing_station", models.CharField(max_length=25)),
                ("elevation", models.CharField(max_length=25)),
                ("notes", models.TextField()),
            ],
        ),
    ]
