# Generated by Django 4.1.1 on 2022-09-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beans", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bean",
            old_name="order_num",
            new_name="order_number",
        ),
        migrations.AlterField(
            model_name="bean",
            name="varietal",
            field=models.CharField(
                choices=[
                    ("Blue Mountain", "Blue Mountain"),
                    ("Bourbon", "Bourbon"),
                    ("Catuai", "Catuai"),
                    ("Caturra", "Caturra"),
                    ("Ethiopia Heirloom", "Ethiopia Heirloom"),
                    ("Geisha", "Geisha"),
                    ("Java", "Java"),
                    ("Kona", "Kona"),
                    ("Mocha", "Mocha"),
                    ("Pachamara", "Pachamara"),
                    ("Sidamo", "Sidamo"),
                    ("SL28", "SL28"),
                    ("SL34", "SL34"),
                    ("Sulawesi", "Sulawesi"),
                    ("Sumatra", "Sumatra"),
                    ("Typica", "Typica"),
                    ("", ""),
                ],
                default="1",
                max_length=20,
            ),
        ),
    ]
