# Generated by Django 4.1.1 on 2022-09-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cups", "0002_alter_cup_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cup",
            old_name="description",
            new_name="notes",
        ),
        migrations.RenameField(
            model_name="cup",
            old_name="process",
            new_name="processing_method",
        ),
        migrations.AddField(
            model_name="cup",
            name="preperation_method",
            field=models.CharField(
                choices=[
                    ("Aeropress", "Aeropress"),
                    ("Chemex", "Chemex"),
                    ("French Press", "French Press"),
                    ("V60", "V60"),
                    ("", ""),
                ],
                default="1",
                max_length=15,
            ),
        ),
    ]
